### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by gastoncs** [LRotherfield/Form#7]
Hi I am getting this error.
Attempted to load class "HiddenEntityType" from namespace "Lrotherfield\Component\Form\Type".
Did you forget a "use" statement for another namespace?

Do I need to register the bundle in the App kernel?

**Comment by LRotherfield** [comment]
This is a component not a bundle so you don't need to register it in the App kernel.  Can you provide some code snippets so I can see how you have configured it?

**Comment by gastoncs** [comment]
Sure
This is my buildForm

        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('mbuser')
                ->add('mbrole')
                ->add('branchTree', 'hidden_entity', array(
                    "class" => "MB2/ATRBundle/Entity/BranchTree"
                ));
        }

My service
            lrotherfield.form.type.hidden_entity:
                   class: Lrotherfield\Component\Form\Type\HiddenEntityType
                   arguments:
                       - @doctrine.orm.entity_manager
                   tags:
                       - { name: form.type, alias: hidden_entity }

**Comment by gastoncs** [comment]
This is the error that I am getting

     */
    protected function getLrotherfield_Form_Type_HiddenEntityService()
    {
        return $this->services['lrotherfield.form.type.hidden_entity'] = new \Lrotherfield\Component\Form\Type\HiddenEntityType($this->get('doctrine.orm.default_entity_manager'));
    }
    /**

**Comment by LRotherfield** [comment]
That all looks fine, seems like the component is not loading from the vendors.  Can you confirm that you have my form component in your vendors? And that the composer autoloader has the Lrotherfield namespace?

**Comment by gastoncs** [comment]
Yes Luke your folder is in the vendors
![untitled](https://cloud.githubusercontent.com/assets/1581923/9476689/95ba91c2-4b33-11e5-91ed-2c87fc2fb48b.png)

What is not is the namespace in the autoloader, what should the path be?

**Comment by gastoncs** [comment]
I saw the problem, there was an error on my composer.lock I delete the file and I did a composer update and it update everything including the auto loader, I think is fine now.

**Comment by LRotherfield** [comment]
Great, you are welcome, glad it is working
